Fix typo in requirements.txt
Assuming this is just missing a `k` :)

```
ERROR: Could not find a version that satisfies the requirement mardown==3.3.4
ERROR: No matching distribution found for mardown==3.3.4
```